version: 2

jobs:
  test:
    docker:
      - image: composer
    steps:
      - checkout
      - run: mkdir -p ~/phpunit
      - run: composer install
      - run: composer test-ci
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit

workflows:
  version: 2
  test:
    jobs:
      - test
