version: 2

jobs:
  test:
    docker:
      - image: phpunit/phpunit
    steps:
      - checkout
      - run: mkdir -p ~/phpunit
      - run: composer install
      - run: phpunit test --log-junit ~/phpunit/test-results.xml
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit

workflows:
  version: 2
  test:
    jobs:
      - test
